# Generated by Django 4.1.5 on 2023-01-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charytatywna', '0004_alter_donation_options_remove_donation_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(verbose_name='Ilość'),
        ),
    ]
